steps:
  #Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/microservices-k8s-417906/auth/prodction',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'auth'
    args: [
        'push',
        'asia-south1-docker.pkg.dev/microservices-k8s-417906/auth/prodction',
      ]
