# services:
#   auth: 
#     build: 
#       context: .
#       dockerfile: ./apps/auth/Dockerfile
#       target: development
#     command: pnpm run start:dev auth
#     env_file: ./apps/auth/.env
#     ports:
#       - 3001:3001 
#     volumes:
#       - .:/usr/src/app
#   mongo:
#     image: mongo

version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm install --prefix apps/auth && pnpm run start:dev auth"
    env_file: ./apps/auth/.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
  mailing:
    build:
      context: . 
      dockerfile: ./apps/mailing/Dockerfile
      target: development
    command: sh -c "pnpm install --prefix apps/mailing && pnpm run start:dev mailing"
    env_file: ./apps/mailing/.env
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
  # mongo:
  #   image: mongo

# volumes:
#   node_modules:
