services:
  auth: 
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file: ./apps/auth/.env
    ports:
      - 3001:3001 
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
