apiVersion: v1
kind: Service
metadata:
  labels:
    app: public
  name: public-http
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - name: 'http'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: auth
  type: NodePort
