apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailing
  name: mailing
spec:
  ports:
    - name: 'tcp'
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: mailing
  type: ClusterIP
