apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/microservices-k8s-417906/auth/production
          name: production
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              value: "100000"
            - name : MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_URI
            - name : MAILING_HOST
              value: 'mailing'
            - name : MAILING_PORT
              value: '3002'
            - name: PORT
              value: '3001'
          ports:
            - containerPort: 3001
