apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freeapi
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-http
            port:
              number: 3001
